api/tasks/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = 'tasks'

urlpatterns = [
    #
    path('',tasks.as_view(), name='list'),
    #
	path('edit/<int:pk>/',TasksListEdit.as_view(), name='edit'),
]

app/tasks/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'tasks'

urlpatterns = [
    #
    path('', views.index, name='index'),
    #
    path('tasks/',tasks.as_view(), name='list'),
    #
    path('tasks/create/',create.as_view(), name='create'),
    #
    path('tasks/delete/<int:pk>/',delete.as_view(), name='delete'),
	#
	path('tasks/update/<int:pk>/',update.as_view(), name='update'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import include,path
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/tasks/', include('api.tasks.urls')),
    path('api/users/', include('api.users.urls')),
    path('api/auth/token/', obtain_jwt_token),
]

api/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):

    name = models.CharField(max_length=50,null=True)
    status = models.IntegerField(default=0)
    user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)

app/tasks/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    STATUS_ID = (
        (0, 'To-do'),
        (1, 'In-progress'),
        (2, 'Done'),
    )
    name = models.CharField(max_length=50,null=True)
    status = models.IntegerField(default=0, choices=STATUS_ID)
    user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)
    
    @property
    def get_status(self):
        if self.status is 0:
            return 'To-do'
        elif self.status is 1:
            return 'In-progress'
        else:
            return 'Done'

app/tasks/forms.py
from django import forms
from .models import *

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'name',
            'status',
        ]
        labels = {
            'name': 'name',
            'status': 'status',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control'}),
        }

api/tasks/views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import ListAPIView,RetrieveAPIView
from rest_framework.mixins import (
    CreateModelMixin,DestroyModelMixin,UpdateModelMixin
)
from .permissions import IsOwnerOrReadOnly
from .serializers import *
from .models import *

class tasks(CreateModelMixin,ListAPIView):
    queryset = Task.objects.all().order_by('-id')
    serializer_class = TaskSerializer

    def list(self, request):
        queryset = Task.objects.filter(user=request.user).order_by('id')
        serializer = TaskSerializer(queryset,many=True)
        return Response(serializer.data)

    def perform_create(self,serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, *args, **kwargs)

class TasksListEdit(DestroyModelMixin,UpdateModelMixin,RetrieveAPIView):
    queryset = Task
    serializer_class = TaskSerializer
    permission_classes = [IsOwnerOrReadOnly]

    def put(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        return Response(serializer.data)
    
    def delete(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

app/tasks/views.py
from django.shortcuts import render,redirect
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView,ListView,UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from .forms import *
from .models import *
# Create your views here.

def index(request):
    return render(request, 'index.html')


class tasks(LoginRequiredMixin,ListView):
    login_url = '/log_in/'
    model = Task
    template_name = 'tasks/list.html'

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user).order_by('-id')


class create(LoginRequiredMixin,CreateView):
    login_url = '/log_in/'
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:list')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        if form.is_valid():
            task = form.save()
            task.user = self.request.user
            task.save()
            return HttpResponseRedirect(self.get_success_url())
        return self.render_to_response(self.get_context_data(form=form))

class update(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
	login_url = '/log_in/'
	model = Task
	form_class = TaskForm
	template_name = 'tasks/update.html'
	success_url = reverse_lazy('tasks:list')

	def test_func(self):
		task=Task.objects.get(id=self.get_object().pk)
		if task.user == self.request.user:
			return True
		else:
			return False

class delete(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')

    def test_func(self):
        task=Task.objects.get(id=self.get_object().pk)
        if task.user == self.request.user:
            return True
        else:
            return False
    

app/tasks/templates/tasks/create.html
{% extends 'base.html' %}
<div class="row">
    <div class="col-sm">
        {% block content %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-sm-6">
                    <div class="block">

                        <form method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                {{ form.name.errors }}
                                <label for="{{ form.name.id_for_label }}">
                                    Name:
                                </label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                {{ form.status.errors }}
                                <label for="{{ form.status.id_for_label }}">
                                    Status:
                                </label>
                                {{ form.status }}
                            </div>
                            <button type="submit">Add</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
</div>

app/tasks/templates/tasks/delete.html
{% extends 'base.html' %}
<div class="row">
    <div class="col-sm">
        {% block content %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-sm-6">
                    <div class="block">
                        <form method="post">
                            {% csrf_token %}
                            <p>Are you sure you want to delete "{{ object.name }}"?</p>
                            <input type="submit" value="Confirm">
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
</div>

app/tasks/templates/tasks/list.html
{% extends 'base.html' %}
<div class="row">
    <div class="col-sm-12">
        {% block content %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-sm-12">
                    <div class="block">
                        <a href="{% url 'tasks:create' %}" class="badge badge-light mb-2">
                            <h3>Add Task</h3>
                        </a>
                        <table class="table table-striped">
                            <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col"></th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in object_list %}
                                    <tr>
                                        <th scope="row">
                                            <a class="badge badge-danger" 
                                                href="{% url 'tasks:delete' item.id %}">
                                                X
                                            </a>
                                        </th>
                                        <td>
                                            <h4>
                                                <a class="badge badge-primary" 
                                                href="{% url 'tasks:update' item.id %}">
                                                    Edit
                                                </a>
                                            </h4>
                                        </td>
                                        <td>
                                            <h4>
                                                {{item.name}}
                                            </h4>
                                        </td>
                                        <td><h4>{{item.get_status}}</h4></td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
</div>

app/tasks/templates/tasks/update.html
{% extends 'base.html' %}
<div class="row">
    <div class="col-sm">
        {% block content %}
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-sm-6">
                    <div class="block">

                        <form method="post">
                            {% csrf_token %}

                            <div class="form-group">
                                    {{ form.name.errors }}
                                    <label for="{{ form.name.id_for_label }}">Name:</label>
                                    {{ form.name }}
                            </div>
                            <div class="form-group">
                                    {{ form.status.errors }}
                                    <label for="{{ form.status.id_for_label }}">Status:</label>
                                    {{ form.status }}
                            </div>
                            <button type="submit">Update</button>
                        </form>

                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
    </div>
</div>