api/tasks/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = 'tasks'

urlpatterns = [
    #
    path('',tasks.as_view(), name='list'),
    #
	path('edit/<int:pk>/',TasksListEdit.as_view(), name='edit'),
]

api/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
app_name = 'users'

urlpatterns = [
    #
    path('',users.as_view(), name='list'),
    #
	# path('edit/<int:pk>/',UsersListEdit.as_view(), name='edit'),
    #
    path('log_in/', log_in.as_view(), name='log_in'),
]

app/users/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import *
app_name = 'users'

urlpatterns = [
    #
    path('sign_up/', sign_up.as_view(), name='sign_up'),
    #
    path('log_in/', log_in, name='log_in'),
    #
    path('log_out/', log_out, name='log_out'),
]

todo_list/urls.py
from django.contrib import admin
from django.urls import include,path
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/tasks/', include('api.tasks.urls')),
    path('api/users/', include('api.users.urls')),
    path('api/auth/token/', obtain_jwt_token),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="shortcut icon" href="" />
    <title>{% block title %}To-do List{% endblock %}</title>
  </head>
  <body>
    {% include  'navbar.html' %}
    <br>
    {% block content %}
    <h4>	base </h4>
    {% endblock %}
  </body>
  <footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </footer>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="">
        <a class="nav-link" href="{% url 'tasks:list' %}">Task</a>
        <a class="nav-link" href="{% url 'users:sign_up' %}">Users</a>
    </div>
{% endblock %}

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #83d0f2;">
    <div class="linksign">
        <a class="navbar-brand" href="{% url 'tasks:list' %}" style="margin-left: 15%;">
            <!-- Home -->
            <!-- <img src="{% static 'img/notes_logo.png' %}" width="30" height="30" alt=""> -->
            <img src="{% static 'img/list-alt.svg' %}" alt="logo" width="30" height="30" >
        </a>
    </div>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">

            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link linksign" href="{% url 'users:log_out' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item active">
                    <a class="nav-link linksign" href="{% url 'users:sign_up' %}">Sign Up</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link linksign" href="{% url 'users:log_in' %}">Log In</a>
                </li>
            {% endif %}
        </ul>
        <span class="navbar-text" style="color:black;">
            {% block welcome_message %}
                {% if user.is_authenticated %}
                    <h5>Welcome {{ user.username }}!!!</h5>
                {% else %}
                    Tasks Manager
                {% endif %}
            {% endblock %}
        </span>
    </div>
</nav>